modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "doapi"
version = "${version}"
displayName = "Lets Do Api"
authors = "Cristelknight, BaumeisterJO"
logoFile = "pack.png"
description = '''
This is an API for the Let's do mods
'''

[[mods]]
modId = "terraform"
version = "4.2.0"
displayName = "Terraform Wood Api Reforged"
authors = "Prospector, coderbot16, TerraformersMC"
description = '''
Terraform Wood Api, but for forge
'''

[[dependencies.doapi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"