name: Release
on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    environment: gradle

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'


      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Publish to Github Packages
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          ACTOR: ${{ secrets.ACTOR }}         # see: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages
          TOKEN: ${{ secrets.TOKEN }}